---
- hosts: database
  become: true
  vars:
    - root_password: "{{ db.root_password }}"
    - create_app_db: true
    - db_name: "{{ db.name }}"
    - db_user: "{{ db.user }}"
    - db_user_password: "{{ db.pass }}"
  roles:
    - general
    - mysql
  tasks:
    - name: Open mysql port
      ufw: rule=allow port=3306
