---
- name: Install System packages
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Configure timezone
  become: true
  template: src=timezone.j2 dest=/etc/timezone

- name: Configure localtime
  become: true
  file: src=/usr/share/zoneinfo/Europe/Kiev dest=/etc/localtime state=link force=yes backup=yes

- name: Deny all on firewall
  become: true
  ufw: state=enabled policy=deny

- name: Allow ssh
  become: true
  ufw: rule=allow name=OpenSSH
