---
- name: Install System packages
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Configure timezone
  template: src=timezone.j2 dest=/etc/timezone

- name: Configure localtime
  file: src=/usr/share/zoneinfo/Europe/Kiev dest=/etc/localtime state=link force=yes backup=yes

- name: Deny all on firewall
  ufw: state=enabled policy=deny

- name: Allow ssh
  ufw: rule=allow name=OpenSSH
