---
- name: Make sure we have the place for website installation
  become: yes
  file: path=/var/www state=directory owner=www-data group=www-data

- name: Download wordpress
  become: yes
  become_user: www-data
  get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz

- name: Unzip wordpress
  become: yes
  become_user: www-data
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Update wp_config.php
  become: yes
  become_user: www-data
  template: src=wp_config.php.j2 dest=/var/www/wordpress/wp-config.php owner=www-data group=www-data mode=0644

- name: Remove config sample
  become: yes
  become_user: www-data
  file: path=/var/www/wordpress/wp-config-sample.php state=absent
