---
- name: Make sure we have the place for website installation
  become: yes
  file: path=/var/www/wordpress state=directory owner=www-data group=www-data

- name: Download wordpress
  get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz creates=/tmp/wordpress.tar.gz

- name: Unzip wordpress
  become: yes
  become_user: www-data
  command: tar -zxvf /tmp/wordpress.tar.gz /var/www/wordpress/

- name: Update wp_config.php
  template: src=wp_config.php.j2 dest=/var/www/wordpress/wp_config.php owner=www-data group=www-data mode=0644

- name: Upload directory writable by www user
