---
- name: Add php7.0 ppa
  apt_repository: repo=ppa:ondrej/php update_cache=yes

- name: Update apt
  apt: update_cache=yes

- name: Install PHP Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.0-cli
    - php7.0-fpm
    - php7.0-curl
    - php7.0-mysql
    - php7.0-json
    - php7.0-xml
    - php7.0-zip
    - php7.0-mbstring
    - php7.0-opcache
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-intl

- include: configure.yml
