---
- name: ensure timezone is set in cli php.ini
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=date
            option=date.timezone
            value=Europe/Kiev
            backup=yes

- name: Enable opcache
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=opcache
            option=opcache.enable
            value=1
            backup=yes

- name: Display errors
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=PHP
            option=display_errors
            value=On
            backup=yes

- name: Startup errors
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=PHP
            option=display_startup_errors
            value=On
            backup=yes
